SETTING:
  MODEL_DIR_NAME: '../models/' # 学習結果の諸々を保存するディレクトリ
  SUB_DIR_NAME: '../data/submission/' # sample提出ファイル保存ディレクトリ
  RAW_DATA_DIR_NAME: '../data/raw/' # オリジナルデータの格納先ディレクトリ
  FEATURE_DIR_NAME: '../data/features/' # オリジナルデータ
  FIGURE_DIR_NAME: "../data/figures/" # 図表の保存先ディレクトリ
  TARGET: "Y" # 目的変数
  REMOVE_COLS: ['Y',"fnlwgt","index"] 